@extends('admin.master.master')
@section('title', 'Salary Advance / Loan')
@section('body')
<main class="progga-content">
    <div class="mb-4"><h4 class="fw-bold mb-1">Salary Advance / Loan</h4><div class="text-muted small">Employee advance requests, installment schedules and repayments</div></div>
    @include('admin.hr.partials.alerts')

    @can('hr-setting-manage')
    <div class="progga-card mb-4"><div class="progga-card-header"><div class="progga-card-title">Create Advance / Loan Request</div></div><div class="progga-card-body"><form method="POST" action="{{ route('hr.advances.store') }}" class="row g-3 align-items-end">@csrf
        <div class="col-md-3"><label class="form-label">Employee *</label><select name="employee_id" class="form-select" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_code }} - {{ $employee->full_name }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label">Type *</label><select name="advance_type" class="form-select" required><option value="salary_advance">Salary Advance</option><option value="loan">Loan</option></select></div>
        <div class="col-md-2"><label class="form-label">Request Date *</label><input type="text" name="request_date" class="form-control hr-datepicker" value="{{ now()->toDateString() }}" required autocomplete="off" placeholder="DD-MM-YYYY"></div>
        <div class="col-md-2"><label class="form-label">Amount *</label><input type="number" step=".01" min="1" name="amount" class="form-control" required></div>
        <div class="col-md-1"><label class="form-label">Installments *</label><input type="number" min="1" max="120" name="number_of_installments" class="form-control" value="1" required></div>
        <div class="col-md-2"><label class="form-label">Installment Amount</label><input type="number" step=".01" min=".01" name="installment_amount" class="form-control"></div>
        <div class="col-md-3"><label class="form-label">Deduction Start *</label><input type="text" name="deduction_start_date" class="form-control hr-datepicker" value="{{ now()->addMonth()->startOfMonth()->toDateString() }}" required autocomplete="off" placeholder="DD-MM-YYYY"></div>
        <div class="col-md-7"><label class="form-label">Reason</label><input type="text" name="reason" class="form-control"></div>
        <div class="col-md-2"><button class="progga-btn progga-btn-primary w-100">Create Request</button></div>
    </form></div></div>
    @endcan

    <div class="progga-card"><div class="progga-card-body border-bottom"><form method="GET" class="row g-2 align-items-end">
        <div class="col-md-3"><label class="form-label">Employee</label><select name="employee_id" class="form-select"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(request('employee_id')==$employee->id)>{{ $employee->employee_code }} - {{ $employee->full_name }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label">Department</label><select name="department_id" class="form-select"><option value="">All</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(request('department_id')==$department->id)>{{ $department->name }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label">Type</label><select name="advance_type" class="form-select"><option value="">All</option><option value="salary_advance" @selected(request('advance_type')==='salary_advance')>Salary Advance</option><option value="loan" @selected(request('advance_type')==='loan')>Loan</option></select></div>
        <div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All</option>@foreach(['pending','active','paid','rejected'] as $status)<option value="{{ $status }}" @selected(request('status')==$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-2"><button class="progga-btn progga-btn-primary w-100">Filter</button></div>
    </form></div>
    <div class="table-responsive"><table class="progga-table mb-0"><thead><tr><th>Employee</th><th>Type / Date</th><th>Amount</th><th>Installment</th><th>Paid / Remaining</th><th>Schedule</th><th>Status</th><th>Action</th></tr></thead><tbody>
    @forelse($advances as $advance)<tr><td><strong>{{ $advance->employee?->full_name }}</strong><br><small class="text-muted">{{ $advance->employee?->employee_code }} · {{ $advance->employee?->department?->name }}</small></td><td>{{ ucwords(str_replace('_',' ',$advance->advance_type ?? 'salary_advance')) }}<br><small>{{ $advance->request_date->format('d-m-Y') }}</small></td><td>{{ number_format($advance->amount,2) }}</td><td>{{ number_format($advance->installment_amount,2) }} × {{ $advance->number_of_installments }}</td><td>{{ number_format($advance->paid_amount,2) }}<br><span class="text-danger">{{ number_format($advance->remaining_amount,2) }}</span></td><td><small>@forelse($advance->installments->take(3) as $installment){{ $installment->due_date?->format('d-m-Y') ?? 'No date' }}: {{ number_format($installment->amount,2) }} ({{ ucfirst($installment->status) }})<br>@empty Not generated @endforelse @if($advance->installments->count()>3)+{{ $advance->installments->count()-3 }} more @endif</small></td><td><span class="badge text-bg-{{ $advance->status==='paid'?'success':($advance->status==='active'?'info':($advance->status==='pending'?'warning':'secondary')) }}">{{ ucfirst($advance->status) }}</span></td><td>@can('hr-setting-manage')
        @if($advance->status==='pending')<form method="POST" action="{{ route('hr.advances.approve',$advance) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success" onclick="return confirm('Approve and create installment schedule?')"><i class="bi bi-check-lg"></i></button></form><button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#rejectAdvance{{ $advance->id }}"><i class="bi bi-x-lg"></i></button><form method="POST" action="{{ route('hr.advances.destroy',$advance) }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-secondary" onclick="return confirm('Delete this request?')"><i class="bi bi-trash"></i></button></form>@endif
        @if($advance->status==='active' && $advance->remaining_amount>0)<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#repayAdvance{{ $advance->id }}"><i class="bi bi-cash-coin"></i></button>@endif
        @endcan</td></tr>
        @can('hr-setting-manage')
        <div class="modal fade" id="rejectAdvance{{ $advance->id }}" tabindex="-1"><div class="modal-dialog"><form method="POST" action="{{ route('hr.advances.reject',$advance) }}" class="modal-content">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Reject Request</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Reason</label><textarea name="reason" class="form-control"></textarea></div><div class="modal-footer"><button class="progga-btn progga-btn-primary">Reject</button></div></form></div></div>
        <div class="modal fade" id="repayAdvance{{ $advance->id }}" tabindex="-1"><div class="modal-dialog"><form method="POST" action="{{ route('hr.advances.repayment',$advance) }}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">Record Repayment</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-6"><label class="form-label">Paid Date *</label><input type="text" name="paid_date" value="{{ now()->toDateString() }}" class="form-control hr-datepicker" required autocomplete="off" placeholder="DD-MM-YYYY"></div><div class="col-6"><label class="form-label">Amount *</label><input type="number" step=".01" min=".01" max="{{ $advance->remaining_amount }}" name="amount" value="{{ min($advance->installment_amount,$advance->remaining_amount) }}" class="form-control" required></div></div></div><div class="modal-footer"><button class="progga-btn progga-btn-primary">Save Repayment</button></div></form></div></div>
        @endcan
    @empty<tr><td colspan="8" class="text-center py-5 text-muted">No salary advance or loan records found.</td></tr>@endforelse
    </tbody></table></div><div class="progga-card-body">{{ $advances->links() }}</div></div>
</main>
@endsection
