<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:dejavusans,sans-serif;font-size:11px;color:#222} .header{text-align:center;border-bottom:2px solid #222;padding-bottom:10px;margin-bottom:14px}.title{font-size:20px;font-weight:bold}.sub{color:#666}.meta,.summary{width:100%;border-collapse:collapse;margin-bottom:14px}.meta td{padding:4px}.box{border:1px solid #ccc}.table{width:100%;border-collapse:collapse}.table th,.table td{border:1px solid #ccc;padding:7px}.table th{background:#f0f0f0;text-align:left}.right{text-align:right}.total{font-weight:bold;background:#f5f5f5}.footer{margin-top:35px;width:100%}.sign{width:32%;display:inline-block;text-align:center;border-top:1px solid #444;padding-top:5px}.small{font-size:9px;color:#666}
</style></head><body>
<div class="header"><div class="title">{{ $restaurant->restaurant_name ?? $restaurant->name ?? config('app.name') }}</div><div class="sub">Salary Payslip</div></div>
<table class="meta"><tr><td><strong>Employee:</strong> {{ $payroll->employee->full_name }}</td><td><strong>Employee Code:</strong> {{ $payroll->employee->employee_code }}</td></tr><tr><td><strong>Department:</strong> {{ $payroll->employee->department?->name ?? 'N/A' }}</td><td><strong>Designation:</strong> {{ $payroll->employee->designation?->name ?? 'N/A' }}</td></tr><tr><td><strong>Payroll Period:</strong> {{ $payroll->period->name }}</td><td><strong>Payment Status:</strong> {{ ucfirst($payroll->payment_status) }}</td></tr><tr><td><strong>Period:</strong> {{ $payroll->period->start_date->format('d-m-Y') }} to {{ $payroll->period->end_date->format('d-m-Y') }}</td><td><strong>Payment Date:</strong> {{ $payroll->period->payment_date?->format('d-m-Y') ?? 'N/A' }}</td></tr></table>
<table class="table" style="margin-bottom:14px"><tr><th>Working Days</th><th>Present</th><th>Absent</th><th>Leave</th><th>Late</th><th>Overtime</th></tr><tr><td>{{ $payroll->working_days }}</td><td>{{ $payroll->present_days }}</td><td>{{ $payroll->absent_days }}</td><td>{{ $payroll->leave_days }}</td><td>{{ $payroll->late_days }}</td><td>{{ round($payroll->overtime_minutes/60,2) }} hrs</td></tr></table>
<table class="table"><thead><tr><th>Salary Component</th><th>Type</th><th class="right">Quantity</th><th class="right">Rate</th><th class="right">Amount ({{ $settings->currency }})</th></tr></thead><tbody>@foreach($payroll->items as $item)<tr><td>{{ $item->component_name }}</td><td>{{ ucfirst($item->component_type) }}</td><td class="right">{{ rtrim(rtrim(number_format($item->quantity,4),'0'),'.') }}</td><td class="right">{{ number_format($item->rate,2) }}</td><td class="right">{{ number_format($item->amount,2) }}</td></tr>@endforeach<tr class="total"><td colspan="4">Total Earnings</td><td class="right">{{ number_format($payroll->total_earnings,2) }}</td></tr><tr class="total"><td colspan="4">Total Deductions</td><td class="right">{{ number_format($payroll->total_deductions,2) }}</td></tr><tr class="total"><td colspan="4">Net Salary</td><td class="right">{{ number_format($payroll->net_salary,2) }}</td></tr><tr><td colspan="4">Paid Amount</td><td class="right">{{ number_format($payroll->paid_amount,2) }}</td></tr><tr><td colspan="4">Due Amount</td><td class="right">{{ number_format($payroll->due_amount,2) }}</td></tr></tbody></table>
<div class="footer"><div class="sign">Prepared By</div><div class="sign" style="margin-left:2%">Employee Signature</div><div class="sign" style="margin-left:2%">Authorized Signature</div></div>
<p class="small" style="margin-top:25px;text-align:center">Generated on {{ now()->format('d-m-Y h:i A') }}. This is a computer-generated payslip.</p>
</body></html>
