@extends('admin.master.master')
@section('title', $period->name.' Payroll')
@section('body')
<main class="progga-content">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><a href="{{ route('hr.payroll.index') }}" class="text-decoration-none small"><i class="bi bi-arrow-left"></i> Payroll periods</a><h4 class="fw-bold mb-1 mt-1">{{ $period->name }}</h4><div class="text-muted small">{{ $period->start_date->format('d M Y') }} - {{ $period->end_date->format('d M Y') }} · Status: {{ ucfirst($period->status) }}</div></div>
    @can('hr-setting-manage')<div class="d-flex gap-2">@if(!in_array($period->status,['approved','locked']))<form method="POST" action="{{ route('hr.payroll.generate',$period) }}">@csrf<button class="progga-btn progga-btn-primary" onclick="return confirm('Generate or recalculate payroll for all active employees?')"><i class="bi bi-calculator"></i> Generate Payroll</button></form>@endif @if($period->status==='generated')<form method="POST" action="{{ route('hr.payroll.approve',$period) }}">@csrf @method('PATCH')<button class="progga-btn progga-btn-outline" onclick="return confirm('Approve this payroll period?')"><i class="bi bi-check-circle"></i> Approve Period</button></form>@endif</div>@endcan</div>
    @include('admin.hr.partials.alerts')
    @if(session('payroll_errors'))<div class="alert alert-warning"><strong>Some payrolls were not generated:</strong><ul class="mb-0 mt-2">@foreach(session('payroll_errors') as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div class="progga-card"><div class="progga-card-body border-bottom"><form method="GET" class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">Employee</label><select name="employee_id" class="form-select"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(request('employee_id')==$employee->id)>{{ $employee->employee_code }} - {{ $employee->full_name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Payment Status</label><select name="payment_status" class="form-select"><option value="">All</option>@foreach(['unpaid','partial','paid'] as $status)<option value="{{ $status }}" @selected(request('payment_status')==$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-2"><button class="progga-btn progga-btn-primary w-100">Filter</button></div></form></div>
    <div class="table-responsive"><table class="progga-table mb-0"><thead><tr><th>Employee</th><th>Attendance</th><th>Basic</th><th>Earnings</th><th>Deductions</th><th>Net Salary</th><th>Paid / Due</th><th>Status</th><th>Action</th></tr></thead><tbody>
    @forelse($payrolls as $payroll)<tr><td><strong>{{ $payroll->employee?->full_name }}</strong><br><small class="text-muted">{{ $payroll->employee?->employee_code }} · {{ $payroll->employee?->department?->name }}</small></td><td><small>Work: {{ $payroll->working_days }}<br>Present: {{ $payroll->present_days }}<br>Absent: {{ $payroll->absent_days }}<br>Late: {{ $payroll->late_days }}</small></td><td>{{ number_format($payroll->basic_salary,2) }}</td><td>{{ number_format($payroll->total_earnings,2) }}</td><td>{{ number_format($payroll->total_deductions,2) }}</td><td><strong>{{ number_format($payroll->net_salary,2) }}</strong></td><td>{{ number_format($payroll->paid_amount,2) }}<br><small class="text-danger">Due: {{ number_format($payroll->due_amount,2) }}</small></td><td><span class="badge text-bg-{{ $payroll->payment_status==='paid'?'success':($payroll->payment_status==='partial'?'warning':'secondary') }}">{{ ucfirst($payroll->payment_status) }}</span><br><small>{{ ucfirst($payroll->payroll_status) }}</small></td><td>
        <a href="{{ route('hr.payroll.payslip',$payroll) }}" target="_blank" class="btn btn-sm btn-outline-primary" title="Preview payslip"><i class="bi bi-file-earmark-pdf"></i></a>
        @can('hr-setting-manage')
        @if(!in_array($payroll->payroll_status,['approved','locked','paid']))<form method="POST" action="{{ route('hr.payroll.regenerate',$payroll) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-secondary" title="Recalculate"><i class="bi bi-arrow-repeat"></i></button></form>@endif
        @if($payroll->due_amount > 0)<button class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#payPayroll{{ $payroll->id }}" title="Record payment"><i class="bi bi-cash-coin"></i></button>@endif
        @endcan
    </td></tr>
    @can('hr-setting-manage')<div class="modal fade" id="payPayroll{{ $payroll->id }}" tabindex="-1"><div class="modal-dialog"><form method="POST" action="{{ route('hr.payroll.payment',$payroll) }}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">Record Payroll Payment</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-6"><label class="form-label">Payment Date *</label><input type="text" name="payment_date" class="form-control hr-datepicker" value="{{ now()->toDateString() }}" required autocomplete="off" placeholder="DD-MM-YYYY"></div><div class="col-6"><label class="form-label">Amount *</label><input type="number" step=".01" name="amount" max="{{ $payroll->due_amount }}" value="{{ $payroll->due_amount }}" class="form-control" required></div><div class="col-6"><label class="form-label">Method *</label><select name="payment_method" class="form-select" required>@foreach(['cash','bank','mobile_banking','cheque','other'] as $method)<option value="{{ $method }}">{{ ucwords(str_replace('_',' ',$method)) }}</option>@endforeach</select></div><div class="col-6"><label class="form-label">Reference</label><input type="text" name="reference_number" class="form-control"></div><div class="col-12"><label class="form-label">Notes</label><textarea name="notes" class="form-control"></textarea></div></div></div><div class="modal-footer"><button class="progga-btn progga-btn-primary">Save Payment</button></div></form></div></div>@endcan
    @empty<tr><td colspan="9" class="text-center py-5 text-muted">Payroll has not been generated for this period.</td></tr>@endforelse
    </tbody></table></div><div class="progga-card-body">{{ $payrolls->links() }}</div></div>
</main>
@endsection
