@extends('admin.master.master')
@section('title', 'Leave Management')
@section('body')
<main class="progga-content">
    <div class="mb-4"><h4 class="fw-bold mb-1">Leave Management</h4><div class="text-muted small">Leave applications, approval workflow and employee leave balances</div></div>
    @include('admin.hr.partials.alerts')

    @can('hr-setting-manage')
    <div class="row g-3 mb-4">
        <div class="col-xl-7"><div class="progga-card h-100"><div class="progga-card-header"><div class="progga-card-title">Create Leave Request</div></div><div class="progga-card-body"><form method="POST" action="{{ route('hr.leave.store') }}" enctype="multipart/form-data" class="row g-3">@csrf
            <div class="col-md-6"><label class="form-label">Employee *</label><select name="employee_id" class="form-select" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_code }} - {{ $employee->full_name }}</option>@endforeach</select></div>
            <div class="col-md-6"><label class="form-label">Leave Type *</label><select name="leave_type_id" class="form-select" required><option value="">Select leave type</option>@foreach($leaveTypes as $type)<option value="{{ $type->id }}">{{ $type->name }} ({{ $type->is_paid?'Paid':'Unpaid' }})</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">Start Date *</label><input type="text" name="start_date" class="form-control hr-datepicker" required autocomplete="off" placeholder="DD-MM-YYYY"></div><div class="col-md-3"><label class="form-label">End Date *</label><input type="text" name="end_date" class="form-control hr-datepicker" required autocomplete="off" placeholder="DD-MM-YYYY"></div>
            <div class="col-md-6"><label class="form-label">Attachment</label><input type="file" name="attachment" class="form-control" accept=".jpg,.jpeg,.png,.pdf,.doc,.docx"></div>
            <div class="col-12"><label class="form-label">Reason *</label><textarea name="reason" class="form-control" rows="3" required></textarea></div><div class="col-12"><button class="progga-btn progga-btn-primary">Submit Leave Request</button></div>
        </form></div></div></div>
        <div class="col-xl-5"><div class="progga-card h-100"><div class="progga-card-header"><div class="progga-card-title">Allocate / Adjust Leave Balance</div></div><div class="progga-card-body"><form method="POST" action="{{ route('hr.leave.balance') }}" class="row g-3">@csrf
            <div class="col-12"><label class="form-label">Employee *</label><select name="employee_id" class="form-select" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_code }} - {{ $employee->full_name }}</option>@endforeach</select></div>
            <div class="col-md-7"><label class="form-label">Leave Type *</label><select name="leave_type_id" class="form-select" required>@foreach($leaveTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Year *</label><input type="number" name="year" class="form-control" value="{{ now()->year }}" required></div>
            <div class="col-md-4"><label class="form-label">Opening</label><input type="number" step=".5" name="opening_balance" class="form-control" value="0"></div><div class="col-md-4"><label class="form-label">Allocated</label><input type="number" step=".5" name="allocated_days" class="form-control"></div><div class="col-md-4"><label class="form-label">Adjustment</label><input type="number" step=".5" name="adjusted_days" class="form-control" value="0"></div>
            <div class="col-12"><button class="progga-btn progga-btn-outline">Save Balance</button></div>
        </form></div></div></div>
    </div>
    @endcan

    <div class="progga-card mb-4"><div class="progga-card-header"><div class="progga-card-title">Leave Requests</div></div><div class="progga-card-body border-bottom"><form method="GET" class="row g-2 align-items-end">
        <div class="col-md-3"><label class="form-label">Employee</label><select name="employee_id" class="form-select"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(request('employee_id')==$employee->id)>{{ $employee->employee_code }} - {{ $employee->full_name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Department</label><select name="department_id" class="form-select"><option value="">All</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(request('department_id')==$department->id)>{{ $department->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All</option>@foreach(['pending','approved','rejected','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status')==$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">From</label><input type="text" name="from_date" class="form-control hr-datepicker" value="{{ request('from_date') }}" autocomplete="off" placeholder="DD-MM-YYYY"></div><div class="col-md-2"><label class="form-label">To</label><input type="text" name="to_date" class="form-control hr-datepicker" value="{{ request('to_date') }}" autocomplete="off" placeholder="DD-MM-YYYY"></div><div class="col-md-1"><button class="progga-btn progga-btn-primary w-100">Filter</button></div>
    </form></div><div class="table-responsive"><table class="progga-table mb-0"><thead><tr><th>Employee</th><th>Leave Type</th><th>Period</th><th>Days</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($requests as $leave)<tr><td><strong>{{ $leave->employee?->full_name }}</strong><br><small class="text-muted">{{ $leave->employee?->employee_code }} · {{ $leave->employee?->department?->name }}</small></td><td>{{ $leave->leaveType?->name }}</td><td>{{ $leave->start_date->format('d-m-Y') }}<br>{{ $leave->end_date->format('d-m-Y') }}</td><td>{{ $leave->total_days }}</td><td>{{ \Illuminate\Support\Str::limit($leave->reason,60) }} @if($leave->attachment)<br><a href="{{ asset('public/'.$leave->attachment) }}" target="_blank">View attachment</a>@endif</td><td><span class="badge text-bg-{{ $leave->status==='approved'?'success':($leave->status==='pending'?'warning':($leave->status==='rejected'?'danger':'secondary')) }}">{{ ucfirst($leave->status) }}</span>@if($leave->rejection_reason)<br><small class="text-danger">{{ $leave->rejection_reason }}</small>@endif</td><td>@can('hr-setting-manage')
            @if($leave->status==='pending')<form method="POST" action="{{ route('hr.leave.approve',$leave) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success" onclick="return confirm('Approve this leave request?')"><i class="bi bi-check-lg"></i></button></form><button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#rejectLeave{{ $leave->id }}"><i class="bi bi-x-lg"></i></button>@endif
            @if(in_array($leave->status,['pending','approved']))<form method="POST" action="{{ route('hr.leave.cancel',$leave) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary" onclick="return confirm('Cancel this leave request?')"><i class="bi bi-slash-circle"></i></button></form>@endif
            @endcan</td></tr>
            @can('hr-setting-manage')<div class="modal fade" id="rejectLeave{{ $leave->id }}" tabindex="-1"><div class="modal-dialog"><form method="POST" action="{{ route('hr.leave.reject',$leave) }}" class="modal-content">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Reject Leave Request</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Rejection Reason *</label><textarea name="rejection_reason" class="form-control" required></textarea></div><div class="modal-footer"><button class="progga-btn progga-btn-primary">Reject Request</button></div></form></div></div>@endcan
        @empty<tr><td colspan="7" class="text-center py-5 text-muted">No leave requests found.</td></tr>@endforelse</tbody></table></div><div class="progga-card-body">{{ $requests->links() }}</div></div>

    <div class="progga-card"><div class="progga-card-header"><div class="progga-card-title">Leave Balances - {{ request('balance_year',now()->year) }}</div></div><div class="table-responsive"><table class="progga-table mb-0"><thead><tr><th>Employee</th><th>Leave Type</th><th>Opening</th><th>Allocated</th><th>Used</th><th>Adjustment</th><th>Remaining</th></tr></thead><tbody>@forelse($balances as $balance)<tr><td><strong>{{ $balance->employee?->full_name }}</strong><br><small class="text-muted">{{ $balance->employee?->employee_code }}</small></td><td>{{ $balance->leaveType?->name }}</td><td>{{ $balance->opening_balance }}</td><td>{{ $balance->allocated_days }}</td><td>{{ $balance->used_days }}</td><td>{{ $balance->adjusted_days }}</td><td><strong>{{ $balance->remaining_days }}</strong></td></tr>@empty<tr><td colspan="7" class="text-center py-4 text-muted">No leave balance records found.</td></tr>@endforelse</tbody></table></div><div class="progga-card-body">{{ $balances->links() }}</div></div>
</main>
@endsection
